DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CART_ITEM;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS DEMO_ORDER;
DROP TABLE IF EXISTS ORDER_PRODUCT;

 
CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  version_id VARCHAR,
  product_name VARCHAR(250) NOT NULL,
  price NUMBER NOT NULL,
  picture_url VARCHAR(500) DEFAULT NULL,
  user_id INT NOT NULL
);

CREATE TABLE CART_ITEM (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  product_id INT NOT NULL,
  user_id INT NOT NULL
);

CREATE TABLE USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR NOT NULL,
  seller BOOLEAN DEFAULT false
);

CREATE TABLE DEMO_ORDER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  status VARCHAR(50) NOT NULL,
  date_created DATE,
  user_id INT NOT NULL 
);

CREATE TABLE ORDER_PRODUCT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  order_id INT NOT NULL,
  quantity NUMBER
  
);